[package]
name = "ahc001"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proconio = "0.3.6"
rand = "0.8"
petgraph = "0.5.0"